import { GoogleGenAI, Type } from "@google/genai";
import { DetectedToken, TokenCategory } from "@/types/tokens";

const ai = new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY! });

const TOKEN_CATEGORIES: TokenCategory[] = [
  "spatial_position", "spatial_size", "spatial_depth", "color",
  "camera_angle", "style",
];

export async function detectTokens(prompt: string): Promise<DetectedToken[]> {
  const response = await ai.models.generateContent({
    model: "gemini-2.5-flash",
    contents: `You are a text-to-image prompt analyzer. Given a user's prompt, identify ambiguous visual tokens that would benefit from visual specification rather than text alone.

For each ambiguous token, return:
- text: the exact substring from the prompt
- startIndex: character index where the token starts in the prompt
- endIndex: character index where the token ends
- category: one of ${TOKEN_CATEGORIES.join(", ")}
- subcategory: specific sub-type
- underspecification: what exactly is ambiguous about this token
- suggestedWidget: brief description of what visual control would help

CRITICAL RULES:
- Only flag tokens that are genuinely ambiguous for image generation
- Don't flag every color word — only when the exact shade matters and is underspecified
- Spatial terms like "next to", "in the corner" are almost always ambiguous
- Camera terms like "close-up", "bird's eye" need precise angle specification
- Style terms like "cinematic", "watercolor" benefit from visual reference
- Focus on the MOST impactful ambiguities (max 5-6 tokens per prompt)
- Tokens must NOT overlap in character ranges

Prompt: "${prompt}"

Return ONLY a JSON array of detected tokens. No markdown, no explanation.`,
    config: {
      responseMimeType: "application/json",
      responseSchema: {
        type: Type.ARRAY,
        items: {
          type: Type.OBJECT,
          properties: {
            text: { type: Type.STRING },
            startIndex: { type: Type.INTEGER },
            endIndex: { type: Type.INTEGER },
            category: { type: Type.STRING },
            subcategory: { type: Type.STRING },
            underspecification: { type: Type.STRING },
            suggestedWidget: { type: Type.STRING },
          },
          required: ["text", "startIndex", "endIndex", "category", "subcategory", "underspecification", "suggestedWidget"],
        },
      },
    },
  });

  try {
    const tokens = JSON.parse(response.text ?? "[]") as DetectedToken[];
    return tokens.filter((t) => TOKEN_CATEGORIES.includes(t.category as TokenCategory));
  } catch {
    return [];
  }
}

export async function generateWithGemini(prompt: string): Promise<string> {
  const response = await ai.models.generateContent({
    model: "gemini-2.5-flash-preview-image-generation",
    contents: prompt,
    config: {
      responseModalities: ["TEXT", "IMAGE"],
    },
  });

  for (const part of response.candidates?.[0]?.content?.parts ?? []) {
    if (part.inlineData) {
      const base64 = part.inlineData.data;
      const mimeType = part.inlineData.mimeType;
      return `data:${mimeType};base64,${base64}`;
    }
  }

  throw new Error("No image generated by Gemini");
}

/**
 * Use Gemini to judge whether a generated image matches the intended prompt and widget instructions.
 * Returns structured evaluation.
 */
export async function judgeImage(
  imageUrl: string,
  originalPrompt: string,
  enrichedPrompt: string,
  widgetInstructions: { widget: string; instruction: string }[],
): Promise<{
  overallScore: number;
  overallPass: boolean;
  widgetScores: { widget: string; instruction: string; score: number; pass: boolean; reasoning: string }[];
  summary: string;
}> {
  const instructionsList = widgetInstructions
    .map((w, i) => `${i + 1}. [${w.widget}] ${w.instruction}`)
    .join("\n");

  // Fetch the image and convert to base64 for Gemini
  let imageData: { data: string; mimeType: string } | null = null;
  try {
    const res = await fetch(imageUrl);
    const buffer = Buffer.from(await res.arrayBuffer());
    const mimeType = res.headers.get("content-type") || "image/png";
    imageData = { data: buffer.toString("base64"), mimeType };
  } catch {
    return {
      overallScore: 0,
      overallPass: false,
      widgetScores: widgetInstructions.map(w => ({
        widget: w.widget, instruction: w.instruction, score: 0, pass: false, reasoning: "Could not fetch image",
      })),
      summary: "Failed to fetch image for judging",
    };
  }

  const response = await ai.models.generateContent({
    model: "gemini-2.5-flash",
    contents: [
      {
        role: "user",
        parts: [
          {
            inlineData: {
              data: imageData.data,
              mimeType: imageData.mimeType,
            },
          },
          {
            text: `You are an expert image quality judge for a text-to-image system. Evaluate whether this generated image follows the given instructions.

Original prompt: "${originalPrompt}"
Enriched prompt sent to model: "${enrichedPrompt}"

Widget-specific instructions to verify:
${instructionsList}

For EACH widget instruction, score from 0-10:
- 0-3: Instruction clearly NOT followed
- 4-6: Partially followed or ambiguous
- 7-10: Clearly followed

Be strict and precise. Look carefully at spatial positions, colors, camera angles, and art styles.
For spatial: check if objects are in the specified positions (left/center/right, foreground/background).
For color: check if the specified colors are present on the right objects.
For camera: check if the viewing angle, lens perspective match the description.
For style: check if the artistic style matches what was requested.`,
          },
        ],
      },
    ],
    config: {
      responseMimeType: "application/json",
      responseSchema: {
        type: Type.OBJECT,
        properties: {
          widgetScores: {
            type: Type.ARRAY,
            items: {
              type: Type.OBJECT,
              properties: {
                widget: { type: Type.STRING },
                instruction: { type: Type.STRING },
                score: { type: Type.INTEGER },
                pass: { type: Type.BOOLEAN },
                reasoning: { type: Type.STRING },
              },
              required: ["widget", "instruction", "score", "pass", "reasoning"],
            },
          },
          overallScore: { type: Type.INTEGER },
          overallPass: { type: Type.BOOLEAN },
          summary: { type: Type.STRING },
        },
        required: ["widgetScores", "overallScore", "overallPass", "summary"],
      },
    },
  });

  try {
    return JSON.parse(response.text ?? "{}");
  } catch {
    return {
      overallScore: 0,
      overallPass: false,
      widgetScores: [],
      summary: "Failed to parse judge response",
    };
  }
}
